# автогенерируемый pin (exact match) на конкретный CSS
# pin-hash: f5f08666181690de5fdee74cc120fa9f8bf60e25
location = /_next/static/css/c42a964c46221ffb.css {
  alias /opt/dune-admin/.next/static/css/pin.css;
  access_log off;
  default_type text/css;
  add_header X-Where "pin" always;
  add_header X-Pin-Hash "f5f08666181690de5fdee74cc120fa9f8bf60e25" always;
  add_header Cache-Control "public, max-age=31536000, immutable";
  open_file_cache off;
  sendfile off;
}
location ^~ /_next/static/css/ {
  alias /opt/dune-admin/.next/static/css/;
  access_log off;
  add_header X-Where "css-dir" always;
  add_header Cache-Control "public, max-age=31536000, immutable";
}
